/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mindarc_screenrecorder_core_ScreenRecorder */

#ifndef _Included_com_mindarc_screenrecorder_core_ScreenRecorder
#define _Included_com_mindarc_screenrecorder_core_ScreenRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mindarc_screenrecorder_core_ScreenRecorder
 * Method:    init
 * Signature: (IIIIZLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mindarc_screenrecorder_core_ScreenRecorder_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jstring);

/*
 * Class:     com_mindarc_screenrecorder_core_ScreenRecorder
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mindarc_screenrecorder_core_ScreenRecorder_start
  (JNIEnv *, jclass);

/*
 * Class:     com_mindarc_screenrecorder_core_ScreenRecorder
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mindarc_screenrecorder_core_ScreenRecorder_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
